### ISSUE TITLE
Ability to exclude some structs 

### ISSUE THREAD

**Issue by ferid-akifzade** [netwo-io/apistos#107]
Hello,

I am trying to use apistos and actix-identity at the same time. 
When I use

```
#[api_operation(tag = "another", summary = "Operator index endpoint")]
pub async fn test(user: Identity) -> HttpResponse {
```
It gives me error. 
"no function or associated item named `request_body` found for struct `actix_identity::Identity` in the current scope".

For successfully compile the code I have to add skip=true. But now my function is not documented at openapi. Please add ability to ignore variable name or structs. Ignoring Identity struct will solve my problem.

**Comment by rlebran** [comment]
Available with Apistos 0.3.1
