### ISSUE TITLE
Still have errors with actix-web-grants

### ISSUE THREAD

**Issue by ferid-akifzade** [netwo-io/apistos#112]
Hello,

Thank for fixing most of the errors, but there is some left. 

error[E0599]: no function or associated item named `responses` found for struct `ResponseWrapper` in the current scope

error[E0599]: no function or associated item named `schema` found for struct `ResponseWrapper` in the current scope
error[E0599]: no function or associated item named `child_schemas` found for struct `ResponseWrapper` in the current scope
error[E0599]: no function or associated item named `error_schemas` found for struct `ResponseWrapper` in the current scope

Error is like: 
 function or associated item not found in `ResponseWrapper<Box<dyn futures_util::Future<Output = actix_web::Either<Result<HttpResponse, actix_web::Error>, HttpResponse>> + Unpin>, __openapi_accept_presentation>`

**Comment by rlebran** [comment]
Hey ! Should be fixed in 0.3.3
