### ISSUE TITLE
Paths with regex

### ISSUE THREAD

**Issue by AzHicham** [netwo-io/apistos#119]
Hello, 

I don't know if it's an Apistos issue or swagger, but when using path containing regex like this one: 

```rust
scope("/imgsrv").service(resource("{path:.+}/tile").route(get().to(endpoints::tile::<T>)))
```

It generate this swagger: 

![image](https://github.com/user-attachments/assets/24a2fb62-5f9e-4271-b15a-2a150d8526be)

As you can see the curl request is wrong, the `{path:.+}` is not replaced by `test.tif`. 
It works well if I use the syntax `{path}`.
One way to fix it may be to sanitize before generating the openapi.json WDYT ? 

Thank you

**Comment by axelfaure** [comment]
Hi ! 
Thanks for the report.

As I understand it, it is an apistos issue as openapi does not allow regex like strings in path parameter's name.

While dropping the regex part of the parameter would be a first step toward correctness, I guess the best way to handle this issue would be to move the regex to an openapi [pattern](https://swagger.io/docs/specification/data-models/data-types/#pattern)

**Comment by AzHicham** [comment]
Nice I didn't know OpenApi had regex handling. 
Sure It can be a great move.

**Comment by rlebran** [comment]
Hi ! 

Back from holidays, I'm having a look.
I plan on sanitizing the path as well as adding the pattern on the parameter definition.
