### ISSUE TITLE
Error using actix session

### ISSUE THREAD

**Issue by francesco-gaglione** [netwo-io/apistos#138]
When using actix_session:

```rust
use actix_session::Session;

#[api_operation(
    tag = "user",
    summary = "User login",
    description = r###"User login"###,
    error_code = 405
)]
pub async fn user_login_api(
    db: Data<DbPool>,
    info: Json<UserLoginDto>,
    session: Session,
) -> Result<Json<CommonResponse<UserLoginResponseDto>>, ErrorResponse> {
... 
}
```

`rustc: no function or associated item named `child_schemas` found for struct `actix_session::Session` in the current scope
function or associated item not found in `Session``

**Comment by rlebran** [comment]
Hi,

Thanks for the report.
I will add the missing implementation for actix_session soon. 

What is your apistos version ?
We are planning on switching to 1.0 in the upcoming month.

**Comment by francesco-gaglione** [comment]
I'm using `v0.4`

**Comment by maxclaey** [comment]
@rlebran Thanks for adding Session support. However, from a usage perspective, it looks like it was added under a feature called `actix-session` for apistos-core, but this feature is not enabled, nor re-exported, for the main `apistos` library. How do I enable this feature?
