### ISSUE TITLE
Swagger UI for apistos like utoipa_swagger_ui

### ISSUE THREAD

**Issue by hectordufau** [netwo-io/apistos#65]
Hi.

Is it possible to use utoipa_swagger_ui (actix-web feature) with apistos, or do you have plan to implement a new one?

 I tried something like this with no success:

`
let swagger = SwaggerUi::new("/{_:.*}").url("/openapi.json", ApiDoc::openapi());
App::new()
            .service(scope("/docs")
                .service(resource("").to(swagger))
            )
            .build("/openapi.json")
`
![image](https://github.com/netwo-io/apistos/assets/12888215/2244d600-f035-48a7-9784-6f0762941647)

Would you like to share a suggestion?

**Comment by hectordufau** [comment]
Hi !

Utoipa was only a try.....I understand that it is no possible...don't worry.

However I think adding an swagger UI as a part of apistos solution will be great, becoming apistos + actix  like FastAPI for Python.

Thanks for attention.

**Comment by rlebran** [comment]
Rapidoc, Redoc and Swagger have been added with the possibility to add any other UI using apistos-plugins. This will be available in a 0.2.0 version in a few minutes.
