### ISSUE TITLE
Question: Is it possible to set it up on a shuttle.rs environment?

### ISSUE THREAD

**Issue by wermerb** [netwo-io/apistos#73]
Hi,

I would like to use this crate in a shuttle.rs environment. 
As you can see on the following [link](https://docs.shuttle.rs/examples/actix), in a shuttle based actix-web application you dont have access to the actix web app sturct directly. 
Is there anyway to use this crate through service configuration?

**Comment by wermerb** [comment]
Thank you very much :)

**Comment by rlebran** [comment]
Now available on master, planning a release for later this afternoon !
