### ISSUE TITLE
Possibility to document successful responses.

### ISSUE THREAD

**Issue by gschulze** [netwo-io/apistos#76]
At the moment, it seems that only error responses can be documented using `#[openapi_error(...)]`. It would be useful to also be able to provide a description for successful responses. Moreover, an API might return different successful responses, i.e. 200 and 201 might both be valid. Are there any plans to add this in the future?

**Comment by rlebran** [comment]
Hi ! 
Successful responses can currently be documented.

If your need is to have a description on successful responses, you can add a rustdoc comment on top of the struct. It will be used as a description for the component in the OAS definition.

To document a 200 response, return a `Ok(Json(YOUR_STRUCT))` where `YOUR_STRUCT` derive both [ApiComponent](https://docs.rs/apistos/latest/apistos/derive.ApiComponent.html) and [JsonSchema](https://docs.rs/schemars/latest/schemars/derive.JsonSchema.html).

To document a 201 response, use the [CreatedJson](https://docs.rs/apistos/latest/apistos/actix/struct.CreatedJson.html) struct.

If you have a single endpoint returning both 200 and 201, this is currently not possible.

Don't hesitate if you have more questions !

**Comment by gschulze** [comment]
Thanks, that was the main info I was looking for!

**Comment by rlebran** [comment]
Perfect, closing it for now 😄
