### ISSUE TITLE
The end position of the URL path is missing "/"

### ISSUE THREAD

**Issue by felix-zuo** [netwo-io/apistos#90]
I define the route in the following way.

`web::scope("/ticket").service(resource("/").route(put().to(update_ticket)))`

apistos: `/ticket`
actix-web: `/ticket/`

**Comment by rlebran** [comment]
Hi ! I'm not able to reproduce, the following snippet
``` rust
App::new()
    .document(spec)
    .service(scope("/test").service(resource("/").route(get().to(test))))
    .build(openapi_path);
```
generate the following spec:
```json
"paths": {
    "/test/": {
      "get": {
        "deprecated": false,
        "operationId": "get_test-384eaa01b751656ac68603765102689f",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Test"
                }
              }
            },
            "description": ""
          },
          "405": {
            "description": "Invalid input"
          }
        },
        "tags": [
          "pet"
        ]
      }
    }
  },
```
Could you please provide a snippet or more information to investigate further ?

**Comment by felix-zuo** [comment]
A complete example：

`
use actix_web::{App, Error, HttpServer};
use apistos::app::OpenApiWrapper;
use apistos::info::Info;
use apistos::spec::Spec;
use apistos::web::{put, resource, Scope};
use apistos::{api_operation, web};

pub const PATH_PREFIX: &str = "/api/rest/v1/finance";

#[tokio::main]
async fn main() {
    HttpServer::new(move || {
        let spec = Spec {
            info: Info {
                title: "An API".to_string(),
                version: "1.0.0".to_string(),
                ..Default::default()
            },
            ..Default::default()
        };
        App::new()
            .document(spec)
            .service(router_api_v1())
            .build("/api-docs/openapi.json")
    })
    .bind(("0.0.0.0", 8080)).unwrap()
    .run()
    .await.unwrap();
}

fn router_api_v1() -> Scope {
    web::scope(PATH_PREFIX).service(api_ticket())
}

const SUB_PATH_PREFIX: &str = "/ticket";

pub fn api_ticket() -> Scope {
    web::scope(SUB_PATH_PREFIX).service(resource("/").route(put().to(update_ticket)))
}

///修改行程票据 - done
#[api_operation(tag = "ticket")]
pub async fn update_ticket() -> Result<String, Error> {
    Ok("success".to_string())
}

`

**Comment by felix-zuo** [comment]
Of course, a complete example：

```rust
use actix_web::{App, Error, HttpServer};
use apistos::app::OpenApiWrapper;
use apistos::info::Info;
use apistos::spec::Spec;
use apistos::web::{put, resource, Scope};
use apistos::{api_operation, web};

pub const PATH_PREFIX: &str = "/api/rest/v1/finance";

#[tokio::main]
async fn main() {
    HttpServer::new(move || {
        let spec = Spec {
            info: Info {
                title: "An API".to_string(),
                version: "1.0.0".to_string(),
                ..Default::default()
            },
            ..Default::default()
        };
        App::new()
            .document(spec)
            .service(router_api_v1())
            .build("/api-docs/openapi.json")
    })
    .bind(("0.0.0.0", 8080))
    .unwrap()
    .run()
    .await
    .unwrap();
}

fn router_api_v1() -> Scope {
    web::scope(PATH_PREFIX).service(api_ticket())
}

const SUB_PATH_PREFIX: &str = "/ticket";

pub fn api_ticket() -> Scope {
    web::scope(SUB_PATH_PREFIX).service(resource("/").route(put().to(update_ticket)))
}

///修改行程票据 - done
#[api_operation(tag = "ticket")]
pub async fn update_ticket() -> Result<String, Error> {
    Ok("success".to_string())
}

```

**Comment by felix-zuo** [comment]
It seems the problem has been solved, thank you very much.

**Comment by rlebran** [comment]
Hey ! The problem is solved in a PR, I'm planning on releasing it tomorrow. Have a nice week end !
